services:
  webapp:
    build:
      context: docker/webapp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./web_app:/workspace/web_app:z
      - /home/atp-user-14/sayzek_vlm:/home/atp-user-14/sayzek_vlm:z
    environment:
      - QWEN_ENDPOINT=http://qwen_vlm:8001
      - RSLLAVA_ENDPOINT=http://rsllava_vlm:8002
      - GENERIC_ENDPOINT=http://generic_vlm:8003
    depends_on:
      - qwen_vlm
      - rsllava_vlm
      - generic_vlm

  qwen_vlm:
    build:
      context: docker/qwen
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./docker/qwen:/app
      - /home/atp-user-14/sayzek_vlm:/home/atp-user-14/sayzek_vlm
      - /home/atp-user-14/.cache/huggingface:/root/.cache/huggingface
      - /tmp/nvidia-libs:/usr/local/nvidia/lib64:ro
    devices:
      - "nvidia.com/gpu=all"

  rsllava_vlm:
    build:
      context: docker/rsllava
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./docker/rsllava:/app
      - /home/atp-user-14/sayzek_vlm:/home/atp-user-14/sayzek_vlm
      - /home/atp-user-14/.cache/huggingface:/root/.cache/huggingface
      - /tmp/nvidia-libs:/usr/local/nvidia/lib64:ro
    devices:
      - "nvidia.com/gpu=all"

  generic_vlm:
    build:
      context: docker/generic
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./docker/generic:/app
      - /home/atp-user-14/sayzek_vlm:/home/atp-user-14/sayzek_vlm
      - /home/atp-user-14/.cache/huggingface:/root/.cache/huggingface
      - /tmp/nvidia-libs:/usr/local/nvidia/lib64:ro
    devices:
      - "nvidia.com/gpu=all"
